//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectSem3Entities : DbContext
    {
        public ProjectSem3Entities()
            : base("name=ProjectSem3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutU> AboutUs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Donate> Donates { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramImage> ProgramImages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeProgram> TypePrograms { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDonate> UserDonates { get; set; }
        public virtual DbSet<UserQuestion> UserQuestions { get; set; }
    }
}
